### ISSUE TITLE
[OCSgw] [Prime] Reliable restart of Prime gRPC

### ISSUE THREAD

**Issue by mpeterss** [ostelco/ostelco-core#160]
There is still some issue with restart of gRPC connections. We need to look into this so that we can restart the cluster without breaking the gRPC connection for OCSgw.

This is the log from the OCSgw

ocsgw          | 11 Jun 2018 09:38:48,982 ERROR GrpcDataSource - ActivateObserver error
ocsgw          | io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
ocsgw          | 	at io.grpc.Status.asRuntimeException(Status.java:526)
ocsgw          | 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
ocsgw          | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
ocsgw          | 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
ocsgw          | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
ocsgw          | 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
ocsgw          | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
ocsgw          | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
ocsgw          | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
ocsgw          | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
ocsgw          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ocsgw          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ocsgw          | 	at java.lang.Thread.run(Thread.java:748)
ocsgw          | Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: ocs.endpoints.pantel-2decb.cloud.goog/35.195.49.238:80
ocsgw          | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
ocsgw          | 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
ocsgw          | 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
ocsgw          | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
ocsgw          | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
ocsgw          | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
ocsgw          | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
ocsgw          | 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
ocsgw          | 	... 1 more
ocsgw          | 11 Jun 2018 09:38:48,984 INFO  GrpcDataSource - reconnectActivate called
ocsgw          | 11 Jun 2018 09:38:48,984 INFO  GrpcDataSource - Schedule new Callable initActivate
ocsgw          | 11 Jun 2018 09:38:48,984 ERROR GrpcDataSource - CreditControlRequestObserver error
ocsgw          | io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
ocsgw          | 	at io.grpc.Status.asRuntimeException(Status.java:526)
ocsgw          | 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
ocsgw          | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
ocsgw          | 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
ocsgw          | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
ocsgw          | 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
ocsgw          | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
ocsgw          | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
ocsgw          | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
ocsgw          | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
ocsgw          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ocsgw          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ocsgw          | 	at java.lang.Thread.run(Thread.java:748)
ocsgw          | Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: ocs.endpoints.pantel-2decb.cloud.goog/35.195.49.238:80
ocsgw          | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
ocsgw          | 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
ocsgw          | 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
ocsgw          | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
ocsgw          | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
ocsgw          | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
ocsgw          | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
ocsgw          | 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
ocsgw          | 	... 1 more
ocsgw          | 11 Jun 2018 09:38:48,985 INFO  GrpcDataSource - reconnectCreditControlRequest called
ocsgw          | 11 Jun 2018 09:38:48,986 INFO  GrpcDataSource - Schedule new Callable initCreditControlRequest
ocsgw          | 11 Jun 2018 09:38:53,984 INFO  GrpcDataSource - Calling initActivate
ocsgw          | 11 Jun 2018 09:38:53,992 ERROR GrpcDataSource - ActivateObserver error
ocsgw          | io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
ocsgw          | 	at io.grpc.Status.asRuntimeException(Status.java:526)
ocsgw          | 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
ocsgw          | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
ocsgw          | 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
ocsgw          | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
ocsgw          | 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
ocsgw          | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
ocsgw          | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
ocsgw          | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
ocsgw          | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
ocsgw          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ocsgw          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ocsgw          | 	at java.lang.Thread.run(Thread.java:748)
ocsgw          | Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: ocs.endpoints.pantel-2decb.cloud.goog/35.195.49.238:80
ocsgw          | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
ocsgw          | 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
ocsgw          | 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
ocsgw          | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
ocsgw          | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
ocsgw          | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
ocsgw          | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
ocsgw          | 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
ocsgw          | 	... 1 more
ocsgw          | 11 Jun 2018 09:38:53,998 INFO  GrpcDataSource - reconnectActivate called
ocsgw          | 11 Jun 2018 09:38:54,000 INFO  GrpcDataSource - Schedule new Callable initActivate
ocsgw          | 11 Jun 2018 09:38:53,996 INFO  GrpcDataSource - Calling initCreditControlRequest
ocsgw          | 11 Jun 2018 09:38:54,001 ERROR GrpcDataSource - CreditControlRequestObserver error
ocsgw          | io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
ocsgw          | 	at io.grpc.Status.asRuntimeException(Status.java:526)
ocsgw          | 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
ocsgw          | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
ocsgw          | 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
ocsgw          | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
ocsgw          | 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
ocsgw          | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
ocsgw          | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
ocsgw          | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
ocsgw          | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
ocsgw          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ocsgw          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ocsgw          | 	at java.lang.Thread.run(Thread.java:748)
ocsgw          | Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: ocs.endpoints.pantel-2decb.cloud.goog/35.195.49.238:80
ocsgw          | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
ocsgw          | 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
ocsgw          | 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
ocsgw          | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
ocsgw          | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
ocsgw          | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
ocsgw          | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
ocsgw          | 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
ocsgw          | 	... 1 more
ocsgw          | 11 Jun 2018 09:38:54,008 INFO  GrpcDataSource - reconnectCreditControlRequest called
ocsgw          | 11 Jun 2018 09:38:54,005 INFO  GrpcDataSource - Calling initKeepAlive
ocsgw          | 11 Jun 2018 09:38:59,006 INFO  GrpcDataSource - Calling initActivate
ocsgw          | 11 Jun 2018 09:38:59,015 ERROR GrpcDataSource - ActivateObserver error
ocsgw          | io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
ocsgw          | 	at io.grpc.Status.asRuntimeException(Status.java:526)
ocsgw          | 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
ocsgw          | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
ocsgw          | 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
ocsgw          | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
ocsgw          | 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
ocsgw          | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
ocsgw          | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
ocsgw          | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
ocsgw          | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
ocsgw          | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
ocsgw          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ocsgw          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ocsgw          | 	at java.lang.Thread.run(Thread.java:748)
ocsgw          | Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: ocs.endpoints.pantel-2decb.cloud.goog/35.195.49.238:80
ocsgw          | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
ocsgw          | 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
ocsgw          | 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
ocsgw          | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
ocsgw          | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
ocsgw          | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
ocsgw          | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
ocsgw          | 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
ocsgw          | 	... 1 more
ocsgw          | 11 Jun 2018 09:38:59,016 INFO  GrpcDataSource - reconnectActivate called
ocsgw          | 11 Jun 2018 09:39:45,452 INFO  OcsApplication - << Received Request

**Comment by mpeterss** [comment]
Done
