### ISSUE TITLE
[Prime] Top up is broken

### ISSUE THREAD

**Issue by mpeterss** [ostelco/ostelco-core#70]
Probably cause by the conversion to Kotlin

prime          | ERROR [2018-04-19 07:33:42,999] com.google.firebase.database.core.ThreadPoolEventTarget: Event handler threw an exception
prime          | ! java.lang.IllegalArgumentException: Parameter specified as non-null is null: method org.ostelco.prime.firebase.FbDatabaseFacade$newProductDefChangedListener$1.onChildAdded, parameter previousChildName
prime          | ! at org.ostelco.prime.firebase.FbDatabaseFacade$newProductDefChangedListener$1.onChildAdded(FbDatabaseFacade.kt)
prime          | ! at com.google.firebase.database.core.ChildEventRegistration.fireEvent(ChildEventRegistration.java:81)
prime          | ! at com.google.firebase.database.core.view.DataEvent.fire(DataEvent.java:65)
prime          | ! at com.google.firebase.database.core.view.EventRaiser$1.run(EventRaiser.java:58)
prime          | ! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prime          | ! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prime          | ! at java.lang.Thread.run(Thread.java:748)

**Comment by mpeterss** [comment]
Fixing null pointer is giving more trouble:

prime          | INFO  [2018-04-19 08:15:13,505] org.ostelco.prime.firebase.FbDatabaseFacade: Just read a product catalog item: org.ostelco.prime.storage.ProductCatalogItem@657d5e79
prime          | WARN  [2018-04-19 08:15:13,505] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for visible_from found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,505] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for image found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,505] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for repurchability found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,505] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for short_description found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,505] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for notes found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,505] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for hidden found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,505] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for expires_on found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,505] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for created_at found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,505] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for description found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,505] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for isVisible found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,506] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for tax_rate found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,506] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for external_url found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,506] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for updated_at found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,506] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for name found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,506] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for categories found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,506] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for id found on class org.ostelco.prime.storage.ProductCatalogItem
prime          | WARN  [2018-04-19 08:15:13,506] com.google.firebase.database.utilities.encoding.CustomClassMapper: No setter/field for value found on class org.ostelco.prime.storage.ProductCatalogItem

**Comment by mpeterss** [comment]
https://github.com/ostelco/ostelco-core/issues/70

**Comment by mpeterss** [comment]
Top up is working again now. But it is not picking up requests at startup only when running. 
This is probably how this worked before and a separate issue.
