### ISSUE TITLE
[OCSgw] Fail to send CCA

### ISSUE THREAD

**Issue by mpeterss** [ostelco/ostelco-core#792]
When HA module fail to fetch the apiId it will throw an illegalStateException. This cause the CCA to failed to get send.

The log will have an attempt log to get:

"Got key : apiId , value : null"

Then the stacktrace :

org.jdiameter.api.InternalException: java.lang.IllegalStateException
    at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.handleEvent(ServerCCASessionImpl.java:325)
    at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.sendCreditControlAnswer(ServerCCASessionImpl.java:132)
    at org.ostelco.ocsgw.datasource.protobuf.ProtobufDataSource.handleCcrAnswer(ProtobufDataSource.kt:58)
    at org.ostelco.ocsgw.datasource.protobuf.PubSubDataSource$1.invoke(PubSubDataSource.kt:64)
    at org.ostelco.ocsgw.datasource.protobuf.PubSubDataSource$1.invoke(PubSubDataSource.kt:30)
    at org.ostelco.ocsgw.datasource.protobuf.PubSubDataSource$setupPubSubSubscriber$receiver$1.receiveMessage(PubSubDataSource.kt:157)
    at com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:379)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:835)
caused by: java.lang.IllegalStateException: null
    at org.ostelco.diameter.ha.common.AppSessionDataReplicatedImpl.getApplicationId(AppSessionDataReplicatedImpl.kt:57)
    at org.jdiameter.common.impl.app.AppSessionImpl.getSessionAppId(AppSessionImpl.java:130)
    at org.jdiameter.common.impl.app.AppSessionImpl.release(AppSessionImpl.java:140)
    at org.jdiameter.common.impl.app.cca.AppCCASessionImpl.release(AppCCASessionImpl.java:90)
    at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.release(ServerCCASessionImpl.java:494)
    at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.setState(ServerCCASessionImpl.java:482)
    at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.setState(ServerCCASessionImpl.java:467)
    at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.handleEvent(ServerCCASessionImpl.java:310)
    ... 12 common frames elided"

**Comment by mpeterss** [comment]
This seems to happen a lot on CCA-T. This is why we see no re-send from P-GW as the session got terminated

**Comment by mpeterss** [comment]
The most likely scenario for this is that Redis was not online when the session was created. Hence the apiId was never stored from the CCR-I.

I will add more logs to trace this better.

apiId is not stored locally. Once this is figured out it should also be stored locally to speed this up.

**Comment by mpeterss** [comment]
I added local storage of apiId and more logs in https://github.com/ostelco/ostelco-core/pull/796
