### ISSUE TITLE
[OCSgw] HA failed to fetch STATE from Redis

### ISSUE THREAD

**Issue by mpeterss** [ostelco/ostelco-core#794]
Getting the STATE value from Redis fail in ServerCCASessionDataReplicatedImpl

val value = getValue(STATE) return null 

I see the following stack.

Caught exception from session object!
java.lang.IllegalStateException: null
    at org.ostelco.diameter.ha.server.ServerCCASessionDataReplicatedImpl.getServerCCASessionState(ServerCCASessionDataReplicatedImpl.kt:50)
    at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.setState(ServerCCASessionImpl.java:472)
    at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.setState(ServerCCASessionImpl.java:467)
    at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl$TccScheduledTask.run(ServerCCASessionImpl.java:361)
    at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.onTimer(ServerCCASessionImpl.java:438)
    at org.ostelco.diameter.ha.timer.ReplicatedTimerTask.runTask(ReplicatedTimerTaskData.kt:99)
    at org.ostelco.diameter.ha.timer.ReplicatedTimerTask.run(ReplicatedTimerTaskData.kt:77)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:835)"

**Comment by mpeterss** [comment]
The TCC_CCASERVER_TIMER is triggered removing the stored state

**Comment by mpeterss** [comment]
The previous CCA-T was a failed send, See https://github.com/ostelco/ostelco-core/issues/792

**Comment by mpeterss** [comment]
This should go away when #792 is fixed

**Comment by mpeterss** [comment]
This still happen as https://github.com/ostelco/ostelco-core/issues/763 will leave the TCC timer running when a session is moved from one instance to another. When the timer is triggered the state is removed. next time the state is needed it was removed from Redis.
