### ISSUE TITLE
[OCSgw] Re-Auth test is not stable

### ISSUE THREAD

**Issue by mpeterss** [ostelco/ostelco-core#81]
I see this test sometimes failing with following output:

26 Apr 2018 10:53:45,234 3696 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  -     30 : Called-Station-Id (UTF8String) . . . . . panacea
26 Apr 2018 10:53:45,234 3696 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  -     18 : 3GPP-SGSN-MCC-MNC (UTF8String) . . . . . 24201
26 Apr 2018 10:53:45,234 3696 [ApplicationSession-1] INFO  org.ostelco.ocsgw.data.local.LocalDataSource  - Sending Credit-Control-Answer
26 Apr 2018 10:53:45,235 3697 [ApplicationSession-1] INFO  org.ostelco.diameter.CreditControlContext  - Credit-Control-Answer
26 Apr 2018 10:53:45,235 3697 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  - 263 : Session-Id (UTF8String) . . . . . . . . . . BadCustomSessionId;1524740025205;0
26 Apr 2018 10:53:45,235 3697 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  - 258 : Auth-Application-Id (Unsigned32). . . . . . 4
26 Apr 2018 10:53:45,235 3697 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  - 268 : Result-Code (Unsigned32). . . . . . . . . . 2001
26 Apr 2018 10:53:45,235 3697 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  - 416 : CC-Request-Type (Integer32) . . . . . . . . 1
26 Apr 2018 10:53:45,235 3697 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  - 415 : CC-Request-Number (Unsigned32). . . . . . . 0
26 Apr 2018 10:53:45,235 3697 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  - 264 : Origin-Host (OctetString) . . . . . . . . . ocs
26 Apr 2018 10:53:45,235 3697 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  - 296 : Origin-Realm (OctetString). . . . . . . . . loltel
26 Apr 2018 10:53:45,235 3697 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  - 456 : Multiple-Services-Credit-Control (Grouped). <Grouped>
26 Apr 2018 10:53:45,235 3697 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  -   432 : Rating-Group (Unsigned32) . . . . . . . . 10
26 Apr 2018 10:53:45,235 3697 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  -   439 : Service-Identifier (Unsigned32) . . . . . 1
26 Apr 2018 10:53:45,236 3698 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  -   431 : Granted-Service-Unit (Grouped). . . . . . <Grouped>
26 Apr 2018 10:53:45,236 3698 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  -     412 : CC-Input-Octets (Unsigned64). . . . . . 0
26 Apr 2018 10:53:45,236 3698 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  -     414 : CC-Output-Octets (Unsigned64) . . . . . 0
26 Apr 2018 10:53:45,236 3698 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  -     421 : CC-Total-Octets (Unsigned64). . . . . . 500000
26 Apr 2018 10:53:45,236 3698 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  -   268 : Result-Code (Unsigned32). . . . . . . . . 2001
26 Apr 2018 10:53:45,236 3698 [ApplicationSession-1] INFO  org.ostelco.diameter.util.DiameterUtilities  -   448 : Validity-Time (Unsigned32). . . . . . . . 86400
26 Apr 2018 10:53:45,249 3711 [FSM-SPeer{Uri=aaa://ocs; State=null; con=null; incConnull }_3-2] INFO  org.ostelco.diameter.test.TestClient  - Received Answer: 272
E2E:2069889051
HBH:26632034
AppID:4
26 Apr 2018 10:53:45,269 3731 [FSM-SPeer{Uri=aaa://ocs; State=null; con=null; incConnull }_3-2] INFO  org.ostelco.diameter.test.TestClient  - AVPS[8]: 
26 Apr 2018 10:53:45,274 3736 [TCPReader-1] INFO  org.jdiameter.client.impl.transport.tcp.TCPTransportClient  - Read thread is stopped for socket [Socket[addr=/127.0.0.1,port=60612,localport=3868]]
26 Apr 2018 10:53:45,274 3736 [ApplicationSession-1] INFO  org.jdiameter.common.impl.app.cca.CCASessionFactoryImpl  - Diameter CCA SessionFactory :: stateChanged :: source[ServerCCASessionImpl [sessionData=org.jdiameter.server.impl.app.cca.ServerCCASessionDataLocalImpl@fe2b7deb]], oldState[IDLE], newState[OPEN]
26 Apr 2018 10:53:45,718 4180 [main] ERROR org.jdiameter.client.impl.controller.PeerTableImpl  - Can not send message
java.lang.NullPointerException
	at org.jdiameter.client.impl.controller.PeerTableImpl.sendMessage(PeerTableImpl.java:233)
	at org.jdiameter.client.impl.StackImpl.sendMessage(StackImpl.java:471)
	at org.jdiameter.client.impl.BaseSessionImpl.genericSend(BaseSessionImpl.java:202)
	at org.jdiameter.client.impl.BaseSessionImpl.genericSend(BaseSessionImpl.java:168)
	at org.jdiameter.client.impl.SessionImpl.send(SessionImpl.java:110)
	at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.dispatchEvent(ServerCCASessionImpl.java:518)
	at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.handleEvent(ServerCCASessionImpl.java:318)
	at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.send(ServerCCASessionImpl.java:508)
	at org.jdiameter.server.impl.app.cca.ServerCCASessionImpl.sendReAuthRequest(ServerCCASessionImpl.java:137)
	at org.ostelco.ocsgw.OcsServer.sendReAuthRequest(OcsServer.java:72)
	at org.ostelco.ocsgw.OcsApplicationTest.testReAuthRequest(OcsApplicationTest.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
	at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:84)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:74)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:47)
	at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
26 Apr 2018 10:53:50,743 9205 [main] INFO  org.jdiameter.client.impl.StackImpl  - (-)(-)(-)(-)(-) Stopping Mobicents DIAMETER Stack v1.7.1-123 (-)(-)(-)(-)(-)
26 Apr 2018 10:53:52,942 11404 [main] INFO  org.jdiameter.client.impl.StackImpl  - (-)(-)(-)(-)(-) Stopped  Mobicents DIAMETER Stack v1.7.1-123 (-)(-)(-)(-)(-)
Failures (1):
  JUnit Jupiter:OcsApplicationTest:testReAuthRequest()
    MethodSource [className = 'org.ostelco.ocsgw.OcsApplicationTest', methodName = 'testReAuthRequest', methodParameterTypes = '']
    => java.lang.AssertionError: expected:<true> but was:<false>
       org.junit.Assert.fail(Assert.java:88)
       org.junit.Assert.failNotEquals(Assert.java:834)
       org.junit.Assert.assertEquals(Assert.java:118)
       org.junit.Assert.assertEquals(Assert.java:144)
       org.ostelco.ocsgw.OcsApplicationTest.waitForRequest(OcsApplicationTest.java:261)
       org.ostelco.ocsgw.OcsApplicationTest.testReAuthRequest(OcsApplicationTest.java:162)
       sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.lang.reflect.Method.invoke(Method.java:498)
       [...]
Test run finished after 12237 ms
[         3 containers found      ]
[         0 containers skipped    ]
[         3 containers started    ]
[         0 containers aborted    ]
[         3 containers successful ]
[         0 containers failed     ]
[         2 tests found           ]
[         0 tests skipped         ]
[         2 tests started         ]
[         0 tests aborted         ]
[         1 tests successful      ]
[         1 tests failed          ]

**Comment by mpeterss** [comment]
[debug.txt](https://github.com/ostelco/ostelco-core/files/1954861/debug.txt)
With debug information enabled

**Comment by mpeterss** [comment]
https://github.com/ostelco/ostelco-core/pull/83

**Comment by mpeterss** [comment]
https://github.com/ostelco/ostelco-core/pull/85
